config/routes.rb
Rails.application.routes.draw do

  resources :albums
  resources :songs

  get 'users/show'
  root 'pages#home'
  get '/pages/texte'

  get '/books', to: 'books#index', as: 'books'
  get '/books/show/:id', to: 'books#show', as: 'show_book'
  get '/books/new', to: 'books#new', as: 'new_book'
  get '/books/edit/:id', to: 'books#edit', as: 'edit_book'
  delete '/books/delete/:id', to: 'books#destroy', as: 'delete_book'
  post '/books/create', as: 'create_book_path'
  patch '/books/update/:id', to: 'books#update', as: 'update_book'

  get '/subjects', to: 'subjects#index', as: 'subjects'
  get '/subjects/show/:id', to: 'subjects#show', as: 'show_subject'
end

app/models/album.rb
class Album < ApplicationRecord
    has_many :songs, dependent: :restrict_with_error
    validates_presence_of :title
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :subject
  validates_presence_of :title
  validates_presence_of :price, :message=> "Error Message"
end

app/models/song.rb
class Song < ApplicationRecord
  validates_presence_of :title
  belongs_to :album
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :books, dependent: :restrict_with_error
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
def index
  @albums = Album.all
end

  def new
    @album = Album.new
  end

def create
   @album = Album.new(album_params)
   if @album.save
     redirect_to action: "index"
   else
     render action: "new"
     end
   end

  def album_params
     params.require(:album).permit(:band, :title, :year)
    end

  def edit
    @album = Book.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      redirect_to action: "index"
    else
      @songs = Song.all render action: "edit"
  end
end

  def destroy
    @Albums = Album.all
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
    @subjects = Subject.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save redirect_to action: "index"
    else
      @subjects = Subject.all
      render action: "new"
      book_params params.require(:book).
      permit(:title, :price, :subject_id, :description)
    end
  end

  def edit
    @book = Book.find(params[:id])
    @subjects = Subject.all
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to action: "index"
    else
      @subjects = Subject.all render action: "edit"
  end
end

  def destroy
    @subjects = Subject.all
end
end

class BooksController < ApplicationController
def index
@books = Book.all
end
 def show
@book = Book.find(params[:id])
end
 def new
@book = Book.new
@subjects = Subject.all
end
 def create
@book = Book.new(book_params)
 if @book.save
redirect_to action: "index"
else @subjects = Subject.all
render action: "new"
end
end
 def book_params
params.require(:book).permit(:title, :price, :subject_id, :description)
end
def edit
@book = Book.find(params[:id])
@subjects = Subject.all
end
 def update
@book = Book.find(params[:id])
if @book.update(book_params)
redirect_to action: "index"
else
@subjects = Subject.all
render action: "edit"
end
end
def destroy
Book.find(params[:id]).destroy
redirect_to action: "index"
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def texte
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

    def new
      @song = Song.new
    end

  def create
     @song = Song.new(song_params)
     if @song.save
       redirect_to action: "index"
     else
       render action: "new"
       end
     end

    def song_params
       params.require(:song).permit(:band, :title, :year)
      end

    def edit
      @song = Song.find(params[:id])
    end

    def update
      @song = Song.find(params[:id])
      if @song.update(song_params)
        redirect_to action: "index"
      else
        @songs = Song.all render action: "edit"
    end
  end

    def destroy
      @song = Song.all
  end
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
    @subjects = Subject.all
  end

  def show
    @subject = Subject.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/edit.html.erb
<%= form_with model: @album, url: "/albums" do |f| %>
<%= f.label :title %>
<%= f.text_field :title %><br>
<%= f.collection_select :album_id, @album, :id, :name %>
<%= f.submit "Album speichern" %>
<%= link_to "Abbrechen", albums_path %>
<% end %>

app/views/albums/index.html.erb
<div class="container">
   <div class="row justify-content-center">
      <h2>Alben</h2>
     </div>
    </div>
    <div class="container">
       <table class="table table-hover">
          <thead class="thead-light">
             <tr>
               <th>Band</th>
                <th>Titel</th>
                 <th>Jahr</th>
                 <th colspan="2">
                 </th> </tr>
                </thead>
                <tbody>
                   <% @albums.each do |a| %>
                    <tr>
                       <td><%= a.band %>
                    </td>
                     <td><%= a.title %></td> <td><%= a.year %>
                    </td>
                     <td><%= link_to "Ändern", edit_album_path(a.id) %>
                    </td>
                     <td><%= link_to "Löschen", album_path(a.id), method: :delete %>
                    </td>
                   </tr>
                   <% end %>
                  </tbody>
                </table>
                <%= link_to "Album erfassen", albums_path %><br />
                  <%= link_to "Songs", songs_path %>
                  </div>

app/views/albums/new.html.erb
<div class="container">
   <div class="row justify-content-center">
      <h2>Album erfassen</h2>
     </div>
   </div>
    <div class="container">
       <%= form_with model: @album, url: albums_path, class: "form-horizontal" do |f| %>
       <div class="row"> <div class="col-md-2 offset-md-1">
         <%= f.label :band, "Band", class: "control-label" %>
        </div>
         <div class="col-md-6">
            <%= f.text_field :band, class: "form-control" %>
          </div> </div> <div class="row">
            <div class="col-md-2 offset-md-1">
              <%= f.label :title, "Titel", class: "control-label" %>
            </div> <div class="col-md-6"> <%= Textfeld für den Titel einfügen, class: "form-control" %> </div>
           </div> <div class="row"> <div class="col-md-2 offset-md-1"> <%= f.label :year, "Jahr", class: "control-label" %> </div>
          <div class="col-md-2"> <%= "Year", class: "form-control" %>
            <br />
          </div>
        </div>
        <div class="row">
      <div class="col-md-2">
    </div>
   <div class="col-md-10">
 <%= f.submit "Album speichern", class: "btn btn-success" %>
<%= link_to "Abbrechen", albums_path, class: "btn btn-danger" %>
 </div>
</div>
<% end %>
 </div>

app/views/books/edit.html.erb
<%= form_with model: @book, url: update_book_path(@book.id) do |f| %>
<%= f.label :title %>
<%= f.text_field :title %><br>
<%= f.label :price %>
<%= f.text_field :price %><br>
<%= f.label :subject %>
<%= f.collection_select :subject_id, @subjects, :id, :name %>
<%= f.label :description %>
<%= f.text_area :description %><br>
<%= f.submit "Buch speichern" %>
<%= link_to "Abbrechen", books_path %>
<% end %>

app/views/books/index.html.erb
<div class="container">
  <table class="table table-hover">
    <thead class="thead-light">
      <tr>
        <th>Titel</th>
        <th colspan="2">Aktion</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |b| %>
      <tr>
        <td><%= link_to b.title, show_book_path(b.id) %></td>
        <td><%= link_to "Ändern", edit_book_path(b.id) %></td>
        <td><%= link_to "Löschen", delete_book_path(b.id), method: :delete, data: { confirm: "Sind Sie sicher?" } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<%= link_to "Neues Buch erfassen", new_book_path %> <br/>

</div>

app/views/books/new.html.erb
<div class="container">
  <h1 class="display-4">Buch erfassen </h1>
</div>
<br>
<%= form_with model: @book, url: create_book_path_url do |f| %>
<%= f.label :title %>
<%= f.text_field :title %><br>
<%= f.label :price %>
<%= f.text_field :price %><br>
<%= f.label :subject %>
<select name="book[subject_id]" id="book_subject_id">
<option value="">Auswahl</option>
<option value="1">Rails</option>s
<option value="2">Linux</option>
<option value="3">SQL</option>
<option value="4">Python</option>
<option value="5">Bash</option>
</select><br>
<%= f.label :description %>
<%= f.text_area :description %><br><%= submit_tag "Buch speichern" %><br>
<%= link_to "Abbrechen", books_path %>
<% end %>

app/views/books/show.html.erb
<div class="container">
  <h2><%= @album.title %></h2>
  <table class="table">
    <tr>
      <td>
        <h4>Preis: </h4>
      </td>
      <td>
      </td>
    </tr>
    <tr>
      <td>
      <td><h4>Created Date:</h4></td>
      <td><h5><%= @album.created_at %></h5></td>
    </tr>
    <tr>
      <td><h4>Beschreibung:</h4></td>
      <td><h5><%= @album.description %></h5></td>
    </tr>
  </table>
  <br /> <%= %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">Carousel</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">Disabled</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/pages/texte">Texte&Tabellen</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/users/show">Userlist</a>
            </li>

          </ul>
          <form class="form-inline mt-2 mt-md-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Carousel Template for Bootstrap</title>
  </head>
  <body>
    <main role="main">

      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="first-slide" src="assets/vevey.png" alt="First slide">
            <div class="container">
              <div class="carousel-caption text-left">
                <h1>Example headline.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img class="second-slide" src="assets/bern.png" alt="Second slide">
            <div class="container">
              <div class="carousel-caption">
                <h1>Another example headline.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img class="third-slide" src="assets/murten.png" alt="Third slide">
            <div class="container">
              <div class="carousel-caption text-right">
                <h1>One more for good measure.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
              </div>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>


      <!-- Marketing messaging and featurettes
      ================================================== -->
      <!-- Wrap the rest of the page in another container to center all the content. -->

      <div class="container marketing">

        <!-- Three columns of text below the carousel -->
        <div class="row">
          <div class="col-lg-4">
            <img class="rounded-circle" src="/assets/placeholder.png" alt="Generic placeholder image" width="140" height="140">
            <h2>Heading</h2>
            <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <img class="rounded-circle" src="/assets/placeholder.png" alt="Generic placeholder image" width="140" height="140">
            <h2>Heading</h2>
            <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <img class="rounded-circle" src="/assets/placeholder.png" alt="Generic placeholder image" width="140" height="140">
            <h2>Heading</h2>
            <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->


        <!-- START THE FEATURETTES -->

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
          </div>
          <div class="col-md-5">
            <img class="rounded-circle" src="/assets/400X400.png" alt="Generic placeholder image">
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7 order-md-2">
            <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
          </div>
          <div class="col-md-5 order-md-1">
            <img class="rounded-circle" src="/assets/400X400.png" alt="Generic placeholder image">
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
          </div>
          <div class="col-md-5">
            <img class="rounded-circle" src="/assets/400X400.png" alt="Generic placeholder image">
          </div>
        </div>

        <hr class="featurette-divider">

        <!-- /END THE FEATURETTES -->

      </div><!-- /.container -->


      <!-- FOOTER -->
      <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy; 2017-2018 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>
    </main>
  </body>
</html>

app/views/users/show.html.erb
<h1>Userlist</h1>
<p>Anzahl Benutzer: <%=User.count%></p>
<p>Name des 1. Benutzers in der Datenbank:	<%=User.first.name%> </P>
<%u=User.first%>
<p> Email des 1. Benutzers in der Datenbank: <%=u.email%></p>
  <p> Alter des 1. Benutzers in der Datenbank: <%=u.age%></p>

<br>
<ol>
  <% User.all.each do |u|%>
    <li> <%=u.name%></li>
    <p>Email: <a href="mailto:<%=u.email%>"><%=u.email%></a></p>
    <li><%=u.age%></li>

  <% end %>
</ol>